[iosevka]
family = 'Iosevka'
version = '1.2.0'
codename = 'Adelin'
copyright = 'Copyright (c) 2015 Belleve Invis.'
licence = '''This font software is licenced under the SIL Open Font Licence, Version 1.1. This is licence is avaliable with a FAQ at: http://scripts.sil.org/OFL. This font software is distributes on an 'AS IS' basis, without warranties or conditions of any kind, either express or implied. See the SIL Open Font licence fot the specific language, premissions and limitations governing your use of this font software.'''

width = 500 # Increase this if you think that Iosevka is too narrow
cap = 735
xheight = 530
#descender = -205 # Unnecessary
accent = 155
accentx = 200
overshoot = -8
overshootx = -8
fovershoot = -40
oxhook = -5

superness = 2.2

longjut = 175
jut = 85
vjut = 145

italicangle = 0
barpos = 0.52
overlaypos = 0.52
ebarpos = 0.45
gbarpos = 0.42
pbarpos = 0.53
fivebarpos = 0.63

lllcrowdedness = 3.33333333

hook = 155
ahook = 130
shook = 110
jhook = 135
fhook = 120
rhook = 90
hookx = 170

smooth = 195
smallsmooth = 220
smoothadjust = 120

tbalance = 50
tbalance2 = 30
rbalance = 40
rbalance2 = 6
sbalance = 0.51
jbalance = 63
fbalance = 6
onebalance = 30

isBold = false
isItalic = false

contrast = 1.11111

[iosevka.variantSelector]

[cjk]
cjk = true

[cc]
family = 'IosevkaCC'
cjk = true
cjkSpacing = true

[slab]
family = "Iosevka Slab"
slab = true
onebalance = 10
overshootx = -16

[x-cc-slab]
family = "IosevkaCC Slab"

# Weights
[w-book]
isBold = false
weight = 400

sb = 60
stroke = 72
dotsize = 125
periodsize = 140
essx = 1.12

[w-bold]
isBold = true
weight = 700

sb = 45
stroke = 108
dotsize = 160
periodsize = 180
essx = 1
jut = 90
vjut = 165

barpos = 0.51
ebarpos = 0.4
fivebarpos = 0.65
oxhook = -3
ahook = 120
rbalance = 60
rbalance2 = 17
rhook = 95
smooth = 210
jbalance2 = 60
tbalance = 50
sbalance = 0.5

# Slant
[s-upright]
isItalic = false

[s-italic]
isItalic = true
italicangle = 10
tbalance = 50
jhook = 90

# Combinations
[x-regular]
style = 'Regular'

[x-bold]
style = 'Bold'

[x-italic]
style = 'Italic'

[x-bolditalic]
style = 'Bold Italic'
ebalance = 0.375
sbalance = 0.53

[x-slab-regular]
style = 'Regular'
sb = 70
rbalance = 60
rbalance2 = 15

[x-slab-bold]
style = 'Bold'
sb = 52
rbalance = 50
rbalance2 = 25

[x-slab-italic]
style = 'Italic'
sb = 70
rbalance = 60
rbalance2 = 25

[x-slab-bolditalic]
style = 'Bold Italic'
ebalance = 0.375
sbalance = 0.53
sb = 52
rbalance = 50
rbalance2 = 35

# Variants
[v-l-hooky.variantSelector]
l = 'hooky'
[v-i-hooky.variantSelector]
dotlessi = 'hooky'
[v-l-zshaped.variantSelector]
l = 'zshaped'
[v-i-zshaped.variantSelector]
dotlessi = 'zshaped'
[v-l-serifed.variantSelector]
l = 'serifed'
[v-i-serifed.variantSelector]
dotlessi = 'serifed'
[v-l-italic.variantSelector]
l = 'italic'
[v-i-italic.variantSelector]
dotlessi = 'italic'