[iosevka]
family = 'Iosevka'
version = 'r0.1.16-p1'
codename = 'Mi-tsieng'
copyright = 'Copyright (c) 2015 Belleve Invis.'

upmscale = 10
width = 500
cap = 724
xheight = 530
descender = -194
accent = 155
accentx = 200
overshoot = -8
oxhook = -5

longjut = 175
jut = 70

italicangle = 0
barpos = 0.52
overlaypos = 0.52
ebarpos = 0.45
gbarpos = 0.42
pbarpos = 0.53
fivebarpos = 0.55

lllcrowdedness = 3.33333333

hook = 145
ahook = 130
shook = 90
jhook = 135
fhook = 120
rhook = 100
hookx = 170

smooth = 195
smallsmooth = 220
smoothadjust = 180

kappa = 0.518
ckappa = 0.618

tbalance = 50
tbalance2 = 30
rbalance = 30
sbalance = 0.51
kappa_hook = 0.7
jbalance = 120
fbalance = 6
onebalance = 30

isBold = false
isItalic = false

vexpansion = 1.11111111111

[iosevka.variantSelector]

[cc]
family = 'IosevkaCC'
cjkSpacing = true

# Weights
[w-book]
isBold = false
weight = 400

sb = 60
stroke = 72
dotsize = 125
periodsize = 140
essx = 1.12

[w-bold]
isBold = true
weight = 700

sb = 50
stroke = 108
dotsize = 160
periodsize = 180
essx = 1.12

barpos = 0.51
ebarpos = 0.4
oxhook = -5
ahook = 120
shook = 110
rbalance = 50
rbalance2 = 12
rhook = 80
smooth = 210
bkappa = 0.5
kappa_hook = 0.7
kappa_ahook = 0.65
kappa_rhook = 0.6
jbalance2 = 60
tbalance = 50
sbalance = 0.5

# Slant
[s-upright]
isItalic = false

[s-italic]
isItalic = true
italicangle = 10
rhook = 80
tbalance = 50
ebarpos = 0.41

# Combinations
[x-regular]
style = 'Regular'

[x-bold]
style = 'Bold'

[x-italic]
style = 'Italic'

[x-bolditalic]
style = 'Bold Italic'
rbalance = 30
ebalance = 0.375
sbalance = 0.53