[iosevka]
family = 'Iosevka'
version = 'r0.1.14'
codename = 'Yuaan-ghei'
copyright = 'Copyright (c) 2015 Belleve Invis.'

upmscale = 10
width = 500
cap = 714
xheight = 520
descender = -194
accent = 155
accentx = 200
overshoot = -8
oxhook = 2

longjut = 175
jut = 70

italicangle = 0
barpos = 0.52
overlaypos = 0.52
ebarpos = 0.45
gbarpos = 0.36
pbarois = 0.55
fivebarpos = 0.55

lllcrowdedness = 3.33333333

hook = 145
ahook = 130
shook = 90
rhook = 100
hookx = 170

smooth = 195
smallsmooth = 220
smoothadjust = 180

kappa = 0.518
ckappa = 0.618

tbalance = 50
tbalance2 = 30
rbalance = 25
sbalance = 0.51
kappa_hook = 0.7

isBold = false
isItalic = false

[iosevka.variantSelector]

[cc]
family = 'IosevkaCC'
cjkSpacing = true

# Weights
[w-book]
isBold = false
weight = 400

sb = 60
stroke = 80
dotsize = 125
periodsize = 140

[w-bold]
isBold = true
weight = 700

sb = 50
stroke = 120
dotsize = 160
periodsize = 180

barpos = 0.51
ebarpos = 0.4
oxhook = 0
ahook = 120
shook = 110
smooth = 210
bkappa = 0.5
kappa_hook = 0.7
kappa_ahook = 0.65
kappa_rhook = 0.6
jbalance = 60
tbalance = 50
rbalance = 18
sbalance = 0.5

# Slant
[s-upright]
isItalic = false

[s-italic]
isItalic = true
italicangle = 10

tbalance = 50
rbalance = 30
ebarpos = 0.41

# Combinations
[x-regular]
style = 'Regular'

[x-bold]
style = 'Bold'

[x-italic]
style = 'Italic'

[x-bolditalic]
style = 'Bold Italic'
rbalance = 25
ebalance = 0.375
sbalance = 0.53